### ISSUE TITLE
Turn on PFCandidates for fatjets

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/PandaTree#5]
Tiny bit bigger, but saves a lot of time offline for special studies.

**Comment by sidnarayanan** [comment]
This is going to take me a little longer. The puppi PF candidate mapping is broken (puppi -> original referencing doesn't work via `CandidatePtr::sourceCandidatePtr`). Trying to implement a workaround

**Comment by sidnarayanan** [comment]
Documenting status...I don't even think we're filling the right puppi weights for the stored PF candidates. We currently pick up whatever is packed, as opposed to using ValueMaps. Trying to fix this too

**Comment by yiiyama** [comment]
You are right, we are filling the puppi weights stored in MINIAOD PF candidates. Since we do rerun puppi (added by makePuppiesForMiniAOD), it is probably better to get the weights from the ValueMap. 

Actually - I think it's simply due to a misconfiguration that we are picking the stored weights. In panda_cfi pfCandidates block, puppi and puppiNoLep PSets are supposed to be puppiMap and puppiNoLepMap.

**Comment by sidnarayanan** [comment]
https://github.com/PandaPhysics/PandaProd/pull/8
