### ISSUE TITLE
Add Vertex Info

### ISSUE THREAD

**Issue by blallen** [PandaPhysics/PandaTree#7]
Monophoton needs to measure rate of correctly identifying the primary vertex in order to improve a background estimate and remove an inefficient cut from the photon ID. 

To first order, I believe we just need to save the reconstructed primary vertex and the generator level primary vertex in MC events. Depending on the results of the first studies, we might also want to include enough information to recalculate the PV in Z events after removing the leptons.

**Comment by yiiyama** [comment]
Working on this now.

**Comment by yiiyama** [comment]
#17 and https://github.com/PandaPhysics/PandaProd/pull/5

**Comment by yiiyama** [comment]
Note: vertex scores are not in order for low-score vertices. This is because we only have access to scores computed on PFCandidates at MINIAOD production stage, while the vertex ordering come from the computation on tracks at RECO stage. Should be a minor effect (at least won't change the primary vertex).
