### ISSUE TITLE
Add genDict to PandaTree

### ISSUE THREAD

**Issue by yiiyama** [PandaPhysics/PandaTree#74]
Hey @sidnarayanan can you add your upgraded genDict script to PandaTree? We've already put the LinkDef and related files in the dict/ directory of Framework and Objects, and there isn't really a reason not to support CLING with Panda.

**Comment by sidnarayanan** [comment]
Since there's only one LinkDef for each of Framework and Objects, could we move them to the top-level (e.g. Framework/LinkDef.h)? This would keep it consistent my other packages.

**Comment by sidnarayanan** [comment]
For reference, here's my upgraded script: https://github.com/sidnarayanan/PandaCore/blob/dev-submission/bin/genDict

It searches for anything in `$CMSSW_BASE/src/*/*/LinkDef.h`

**Comment by yiiyama** [comment]
Fine with me! Please do whatever you see fit.

**Comment by yiiyama** [comment]
I'm going to temporarily package genDict with PandaTree, but maybe having PandaCore (assuming the dev-submission branch is not abandoned) as a standard installation in PandaPhysics is a better solution.

**Comment by sidnarayanan** [comment]
I hadn't yet acted on this issue because Dylan reported some issues when using genDict with PandaTree, which I hadn't looked into yet. I guess for now it can be use-at-your-own-risk.

The dev-submission branch is not abandoned - actually it is the primary branch but I don't have it merged to master yet because of a couple outstanding issues. On the other hand, PandaCore contains a lot of stuff the average user won't need - I think I'm the only one who uses the plotting framework, e.g. Let's discuss this.
