### ISSUE TITLE
Need a release validation mechanism

### ISSUE THREAD

**Issue by yiiyama** [PandaPhysics/PandaTree#83]
I've made too many mistakes which could have been avoided if we simply made a plot dump of all branches. We should write something like event.dumpPlots(tree) that creates histograms for all branches and saves it into a web page.

**Comment by dabercro** [comment]
@yiiyama I started a rough version of this today at this branch: https://github.com/PandaPhysics/PandaTree/compare/branch-008...dabercro:rel-val

The output would be placed at a page like this: http://t3serv001.mit.edu/~dabercro/relval/

Note, that the words "electrons" and "pfCandidates" on http://t3serv001.mit.edu/~dabercro/relval/?d=171116_203624 are clickable. After clicking on each, you can view the relevant plots. I just have terrible taste when it comes to web design. Anyway, the interesting bit is that I have the unpacking for pfCandidates working.

I have the following two goals at this point:

- Automatically generate this file with generate.py: https://github.com/dabercro/PandaTree/blob/rel-val/RelVal/interface/EnumerateBranches.h Hopefully the structure of this file makes sense, but let me know if you're not sure what I'm doing. (Because if you're interested, I'm sure you can get that part done much faster than me. I was thinking of putting event globals like npv as named "common/npv" under panda_plot_names.) The rest of the code shouldn't need much modification as long as that header is correct.
- Clean up the webpage and plots to make everything relatively nice to look at

Let me know if you want me to make a pull request already to give everyone else something to work with.

EDIT for a third goal:

- I should also add meta data about the panda file run over on the webpage.

**Comment by dabercro** [comment]
Actually, I went ahead and threw in a "common/npv" example since it's also not a vector (and I'm excited). Page here: http://t3serv001.mit.edu/~dabercro/relval/?d=171116_205606

**Comment by dabercro** [comment]
I finished my point 2. I'll add the metadata quickly today. Then should I make a pull request for anyone to help out with the plot enumerator?

**Comment by yiiyama** [comment]
Wow, what you have is pretty complicated - does it have to be template-based and recursive? (If you think it's easily manageable by others, I'm fine of course)

**Comment by dabercro** [comment]
I was templating to try to make it fast. The main goal was to minimize the amount of code that needs to be automatically generated (just EnumerateBranches.h). I think as long as we have a mechanism for people to add random plots via some other .def format (Dylan wants di-lepton mass plots, for example), then we should be able to keep everyone happy.

**Comment by dabercro** [comment]
I hate to bring up lepton masses again, but it looks like the muons' are exactly a factor of 10 too low, and I can't figure out why: http://t3serv001.mit.edu/~dabercro/relval/171119_195811/muons/m.pdf

**Comment by dabercro** [comment]
The masses are fine in the MiniAOD files. I'll try to look through our config to see what else touches the muons.

**Comment by dabercro** [comment]
Nevermind. Found it: https://github.com/PandaPhysics/PandaTree/pull/95/commits/a850f10907e62e71e4fb6b7375892a83dd082240 It's also in #95

**Comment by yiiyama** [comment]
Wow, that's a stupid mistake on my side. Thanks for catching it.

**Comment by dabercro** [comment]
Jenkins is running the testpanda nicely now. Example: https://github.com/dabercro/PandaTree/pull/2

It's also compiling PandaTree and PandaProd, so it takes a while. I think it will be much nicer and a little faster if we figure out exactly how we want to test those two repositories. I probably shouldn't be doing this now though.

**Comment by yiiyama** [comment]
Sounds great, yes let's figure out how exactly we want to use it at the next upgrade cycle.
